@startuml
!theme amiga

skin rose

title Connect4

class Connect4
class Game
interface Player
class Bot
class Human
class Board
class Coordinate
class Line
class Row
class Column
class AscendingDiagonal
class DescendingDiagonal
class Turn
class Token
class Put



class Result
class Draw
class Victory

Connect4 *--> "0..n" Game

Result <|-- Victory
Result <|-- Draw

Victory o--> Token : 4

Victory o--> Line

Put ..> Column
Put ..> Token

Coordinate --> Token

Game *--> "0..1" Result
Game *--> Board : 1
Game *--> Turn
Game o--> Player : 2

Board *--> "6 * 7" Token
Board --> Coordinate
Line *-->  Coordinate

Board --> Line
Line <|-- Row
Line <|-- Column
Line <|-- AscendingDiagonal
Line <|-- DescendingDiagonal

Row *--> "7" Coordinate
Column *--> "6" Coordinate

Player ..> Board
Player ..> Put
Player o--> Token : 21
Player --> Color
Player <|-- Bot
Player <|-- Human

Turn o--> Player : 2
Token --> Color

enum Color {
  RED
  BLUE
  NULL
}

@enduml